#!/bin/bash
#
# This script helps new contributors set up their local workstation for
# gophercloud development and contributions.

# Create the environment
export GOPATH=$HOME/go/gophercloud
mkdir -p $GOPATH

# Download gophercloud into that environment
go get github.com/YoungPioneers/huaweicloud-sdk-go
cd $GOPATH/src/github.com/YoungPioneers/huaweicloud-sdk-go
git checkout master

# Write out the env.sh convenience file.
cd $GOPATH
cat <<EOF >env.sh
#!/bin/bash
export GOPATH=$(pwd)
export GOPHERCLOUD=$GOPATH/src/github.com/YoungPioneers/huaweicloud-sdk-go
EOF
chmod a+x env.sh

# Make changes immediately available as a convenience.
. ./env.sh
